import { PERMISSIONS } from './permissions.constants';
import { SYSTEM_ROLES, type SystemRole } from './roles.constants';

const allPermissions = Object.values(PERMISSIONS);

export const ROLE_PERMISSION_MAP: Record<SystemRole, string[]> = {
  [SYSTEM_ROLES.ADMIN]: allPermissions,
  [SYSTEM_ROLES.STAFF]: [
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_WRITE,
    PERMISSIONS.AGENDA_WRITE,
    PERMISSIONS.ACTION_MANAGE,
    PERMISSIONS.REPORT_SUBMIT,
    PERMISSIONS.MINUTES_WRITE,
  ],
  [SYSTEM_ROLES.DIRECTOR]: [
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_READ_IN_CAMERA,
    PERMISSIONS.AGENDA_WRITE,
    PERMISSIONS.RESOLUTION_MANAGE,
    PERMISSIONS.ACTION_MANAGE,
    PERMISSIONS.REPORT_APPROVE_DIRECTOR,
    PERMISSIONS.MINUTES_WRITE,
  ],
  [SYSTEM_ROLES.CAO]: [
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_READ_IN_CAMERA,
    PERMISSIONS.AGENDA_WRITE,
    PERMISSIONS.AGENDA_PUBLISH,
    PERMISSIONS.RESOLUTION_MANAGE,
    PERMISSIONS.ACTION_MANAGE,
    PERMISSIONS.REPORT_APPROVE_CAO,
    PERMISSIONS.MINUTES_ADOPT,
    PERMISSIONS.MINUTES_PUBLISH,
    PERMISSIONS.PUBLIC_PUBLISH,
  ],
  [SYSTEM_ROLES.COUNCIL_MEMBER]: [
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_READ_IN_CAMERA,
    PERMISSIONS.VOTE_RECORD,
  ],
};
